spring:
  application:
    name: PowerToolStore

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

cloudinary:
  url: ${CLOUDINARY_URL}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  cloud-name: ${CLOUDINARY_CLOUD_NAME}

server:
  port: ${PORT:8080}
